### ISSUE TITLE
Move authors into _data folder

### ISSUE THREAD

**Issue by ikhrome** [webgrower/webgrower.github.io#1]
Like this:

`_data/authors/ikhrome.yml` may contain:

``` yml
author_name:
  twitter: author_twitter
  ...
```

This feature will improve data structure, and may be used for future needs.
